window.GAIN_STORE = {
  brand: "Gain",
  discordUrl: "https://discord.gg/PBMHrgJ4Kd",
  stripeFulfillUrl:
    "https://repssuepvwmpfctiztvj.supabase.co/functions/v1/stripe/fulfill",
  stripeDownloadUrl:
    "https://repssuepvwmpfctiztvj.supabase.co/functions/v1/stripe/download",
  salesStatsUrl:
    "https://repssuepvwmpfctiztvj.supabase.co/functions/v1/stripe/stats/sales",
  defaultPlan: "skins",
  plans: {
    skins: {
      id: "skins",
      kicker: "Internal",
      name: "Skin Changer",
      title: "Rivals Skin Changer",
      blurb: "In-game cosmetics, visuals, and spoof tools.",
      price: "$5.00",
      priceWas: "",
      save: "",
      cta: "Pay with card — $5.00",
      stripeUrl: "https://buy.stripe.com/dRm6oGeOv8lW76k106dQQ00",
      loaderUrl:
        "https://repssuepvwmpfctiztvj.supabase.co/functions/v1/license/loader/gain",
      includes: ["Insane performance", "Instant updates", "Lifetime access"],
      setup: [
        "Pay with card or purchase on Discord.",
        "Join Rivals and open your executor.",
        "Run the loader with your key.",
      ],
      features: {
        Cosmetics: [
          "Weapon skins",
          "Wraps",
          "Charms",
          "Live preview",
          "Search & grid picker",
          "Auto-save loadout",
        ],
        Visuals: [
          "Skybox + rotation",
          "Fog, clock, brightness",
          "Bloom, blur, DOF, sun rays",
          "Atmosphere haze / glare",
          "4K reflections",
          "Combat FX cleanup",
        ],
        Chams: [
          "Weapon chams",
          "Arm chams",
          "Invisible arms",
          "Highlights & outlines",
          "14 materials (Neon, Chrome, Prism…)",
        ],
        Camera: ["Third person + bind", "FOV changer", "Stretched resolution"],
        Spoof: [
          "Level / streak / rank",
          "ELO",
          "Name & username",
          "Device type",
          "Custom status",
        ],
        Other: [
          "Config profiles + autoload",
          "Accent color & menu key",
          "Insane performance",
          "Undetected status",
        ],
      },
    },
    external: {
      id: "external",
      kicker: "External",
      name: "Gain External",
      title: "Gain External",
      blurb: "Standalone overlay: ESP, motion, combat, and world tools.",
      price: "$3.50",
      priceWas: "$5.00",
      save: "30% off",
      cta: "Pay with card — $3.50",
      stripeUrl: "https://buy.stripe.com/dRm6oG8q7dGg62g4cidQQ02",
      loaderUrl:
        "https://repssuepvwmpfctiztvj.supabase.co/functions/v1/license/loader/external",
      includes: ["Insane performance", "Instant updates", "Lifetime access"],
      setup: [
        "Pay with card. Your key and download appear on the success page.",
        "Download Gain External (zip). It is not a Roblox script.",
        "Open the app and paste your license key. Do not use script_key or a loader.",
      ],
      features: {
        ESP: [
          "Box, cornered box, fill",
          "Name, healthbar, health number",
          "Distance, snaplines, skeleton",
          "Chams, team check, max distance",
          "Radar, china hat, off-screen",
          "Live ESP preview",
        ],
        Motion: [
          "Speed + fly",
          "Jump power",
          "Teleport to enemy",
          "Orbit + prediction",
          "Noclip, gravity, tickrate",
          "Third person, spinbot",
        ],
        Combat: ["Combat tab tools", "Target HUD", "Lock mouse to player"],
        Visuals: ["Crosshair", "Camera FOV", "World / misc tabs"],
        Other: ["Standalone overlay", "Insane performance", "Undetected status"],
      },
    },
    bundle: {
      id: "bundle",
      kicker: "Both",
      name: "Skin + External",
      title: "Gain Bundle",
      blurb: "Skin Changer and External together. Two keys, one checkout.",
      price: "$7.50",
      priceWas: "$8.50",
      save: "Save $1.00",
      cta: "Pay with card — $7.50",
      stripeUrl: "https://buy.stripe.com/28EbJ049R7hSduI5gmdQQ01",
      loaderUrl:
        "https://repssuepvwmpfctiztvj.supabase.co/functions/v1/license/loader/gain",
      includes: [
        "Insane performance",
        "Both products included",
        "Lifetime access",
      ],
      setup: [
        "Pay once. Skin Changer gets a Roblox loader. External gets a zip + app key.",
        "Use the Skin Changer key with the executor loader only.",
        "Download External from the success page and paste its key in the app — not in Roblox.",
      ],
      features: {
        Included: [
          "Rivals Skin Changer",
          "Gain External overlay",
          "Two separate licenses",
          "Lifetime on both",
        ],
        Value: ["$5.00 + $3.50 separately", "Bundle $7.50", "Save $1.00"],
      },
    },
  },
  executors: [
    "Madium",
    "Potassium",
    "Wave",
    "Real",
    "Volt",
    "Seliware",
    "Cosmic",
    "Delta",
    "Codex",
    "Isaeva",
    "SirHurt",
    "MacSploit",
    "Opiumware",
  ],
};
