window.GAIN_STORE = {
  brand: "Gain",
  product: "Rivals Skin Changer",
  discordUrl: "https://discord.gg/PBMHrgJ4Kd",
  loaderUrl:
    "https://repssuepvwmpfctiztvj.supabase.co/functions/v1/license/loader/gain",
  price: { amount: "5.00", currency: "$" },
  executors: [
    "Madium",
    "Potassium",
    "Wave",
    "Real",
    "Volt",
    "Seliware",
    "Cosmic",
    "Delta",
    "Codex",
    "Isaeva",
    "SirHurt",
    "MacSploit",
    "Opiumware",
  ],
  features: {
    Cosmetics: [
      "Weapon skins",
      "Wraps",
      "Charms",
      "Live preview",
      "Search & grid picker",
      "Auto-save loadout",
    ],
    Visuals: [
      "Skybox + rotation",
      "Fog, clock, brightness",
      "Bloom, blur, DOF, sun rays",
      "Atmosphere haze / glare",
      "4K reflections",
      "Combat FX cleanup",
    ],
    Chams: [
      "Weapon chams",
      "Arm chams",
      "Invisible arms",
      "Highlights & outlines",
      "14 materials (Neon, Chrome, Prism…)",
    ],
    Camera: [
      "Third person + bind",
      "FOV changer",
      "Stretched resolution",
    ],
    Spoof: [
      "Level / streak / rank",
      "ELO",
      "Name & username",
      "Device type",
      "Custom status",
    ],
    Other: [
      "Config profiles + autoload",
      "Accent color & menu key",
      "HWID-locked license",
      "Undetected status",
    ],
  },
};
